### ISSUE TITLE
Navbar overlaps the header

### ISSUE THREAD

**Issue by tikhsuP** [joomla/api.joomla.org#14]
# Subject of the issue

The Header gets partially overlapped by the Navbar for screen sizes between 962px and 1182px.

# Steps to reproduce

Use developer options to check for the sizes from about 1182px to 962px.

# Expected behaviour

The Navbar should not overlap the Header and the Header should be completely visible.

# Actual behaviour

For screen sizes from 962px to 1182px the following result is produced: 
![Screenshot (13)](https://user-images.githubusercontent.com/42881874/74664152-30f42280-51c3-11ea-8807-45a12634ad1e.png)

**Comment by mbabker** [comment]
It's a template issue, this would be better reported on https://github.com/joomla/joomla-websites (FWIW this was working OK at the 980px-1199px viewport at one point but probably got messed up the last time the top level menu items were restructured, the 768px-979px viewport just has search completely hidden because the space is too little for the full menu AND the search position).

**Comment by tikhsuP** [comment]
Thanks @mbabker.
