### ISSUE TITLE
Misoriented buttons

### ISSUE THREAD

**Issue by tikhsuP** [joomla/api.joomla.org#15]
# Subject of the issue

The Download and Launch buttons are disoriented for screen sizes between 304px - 462px.
The Download button is at the center of the screen while the Launch button is slightly shifted to right.

# Steps to reproduce

Check for screen sizes between 462px and 304px.

# Expected behaviour

Both the buttons should be at the perfect center of the screen.

# Actual behaviour

The misorientation can be seen in the following image:

![Screenshot (14)](https://user-images.githubusercontent.com/42881874/74664808-75cc8900-51c4-11ea-9f6a-695d292ebd12.png)

**Comment by mbabker** [comment]
This was actually fixed in the template in November 2018 but the fix has been unable to be deployed due to the continued delay of the compliance team's work on a cookie notification mechanism.

![Screen Shot 2020-02-17 at 9 27 51 AM](https://user-images.githubusercontent.com/368545/74666841-d8dc0280-5167-11ea-87fb-9ad0efc3e1ca.png)

**Comment by tikhsuP** [comment]
Ok, thanks.
